#!/bin/bash

mkdir -p output/

cfgs="unaud-micro-rev.yaml unaud-micro.yaml aud-micro.yaml 
  aud-micro-rev.yaml aud-small.yaml aud-small-rev.yaml unaud-abr.yaml 
  unaud-abr-rev.yaml unaud-full.yaml unaud-full-rev.yaml aud-full.yaml 
  aud-full-rev.yaml ct.yaml esef.yaml esef-fr.yaml"

for cfg in ${cfgs}
do
    echo ${cfg}...
    out=output/${cfg%.yaml}.html
    kv=output/${cfg%.yaml}.kv
    cmp=log/${cfg%.yaml}.kv
    scripts/ixbrl-reporter test/${cfg} report ixbrl > ${out}
    ixbrl-to-kv ${out} | \
	grep -E -v 'VersionProductionSoftware|VersionOfProductionSoftware' | \
	sort > ${kv}
    grep -E -v 'VersionProductionSoftware|VersionOfProductionSoftware' ${cmp} | \
	sort | cmp ${kv} -
    if [ $? -ne 0 ]
    then
        echo 'File comparison fail...'
	echo 'diff ${kv} ${cmp} >>>>'
	grep -E -v 'VersionProductionSoftware|VersionOfProductionSoftware' \
	      ${cmp} | \
	    sort | cmp ${kv} -
	sort ${cmp} | diff ${kv} -
	exit 1
    fi
done

