
accounts:
  # Filename of GnuCash accounts
  kind: piecash
  file: example2.gnucash

# Do you want your accounts in English or French?
#report: //import report/esef/esef.yaml
report: //import report/esef/esef-fr.yaml

#pretty-print: true

metadata: //import detail/metadata-esef.yaml

logo:  //import detail/logo.yaml

