
#############################################################################
### GnuCash accounts source #################################################
#############################################################################
accounts:
  # Filename of GnuCash accounts
#  kind: gnucash
#  file: example.gnucash
  kind: piecash
  file: example2.gnucash

report: //import report/hmrc/corp-tax.yaml

#pretty-print: true

metadata: //import detail/metadata-corptax.yaml

